name: Build and Deploy to EKS 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2
      ECR_REGISTRY: ${{ secrets.ECR_LOGIN }}
      IMAGE_NAME: golu
      EKS_CLUSTER_NAME: my-cluster 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Build Docker image
      run: |
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 423755636060.dkr.ecr.us-east-2.amazonaws.com
        docker build -t golu .
        docker tag golu:latest 423755636060.dkr.ecr.us-east-2.amazonaws.com/golu:latest
        docker push 423755636060.dkr.ecr.us-east-2.amazonaws.com/golu:latest  

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Update kubeconfig for EKS cluster
      run: |
        aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
        ls
        
    - name: Deploy to EKS
      run: |
        sed -i "s|423755636060.dkr.ecr.us-east-2.amazonaws.com/golu:latest|423755636060.dkr.ecr.us-east-2.amazonaws.com/golu:latest|" deploy.yaml      
        kubectl apply -f Acck/deploy.yaml
